services:
  db:
    image: postgres:16-alpine
    container_name: hwc_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hw_checker}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hwc_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://postgres:postgres@db:5432/hw_checker}
    ports:
      - "${BACKEND_PORT:-8082}:8082"

volumes:
  db_data:
